---
title: "Code book"
author: "JZhou"
date: "2/21/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

The run_analysis.R script performs the data preparation and then followed by the 6 steps required as described in the course project’s definition.

1. Download the dataset:  Dataset downloaded and extracted under the folder called "UCI HAR Dataset"

2. Assign each data to variables: 
   # features <- features.txt
     The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ.
   # activities <- activity_labels.txt
     List of activities performed when the corresponding measurements were taken and its codes (labels)
   # subject_test <- test/subject_test.txt
   # x_test <- test/X_test.txt 
   # y_test <- test/y_test.txt
   # subject_train <- test/subject_train.txt 
   # x_train <- test/X_train.txt 
   # y_train <- test/y_train.txt 

3. Merges the training and the test sets to create one data set: Merged_Data

4. Extracts only the measurements on the mean and standard deviation for each measurement

5. Uses descriptive activity names to name the activities in the data set and Appropriately labels the data set with descriptive variable names.

6. creates a second, independent tidy data set with the average of each variable for each active and each subject

7. checking and final look

